# Generated by Django 6.0.7 on 2026-09-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=255)),
                ('number_of_travelers', models.PositiveIntegerField()),
                ('travel_date', models.DateField()),
                ('travel_purpose', models.CharField(choices=[('Leisure', 'Leisure'), ('Business', 'Business'), ('Umrah', 'Umrah'), ('Hajj', 'Hajj'), ('Medical', 'Medical'), ('Other', 'Other')], max_length=50)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
